name: ✨ Solicitar Nova Funcionalidade
description: Propor uma nova funcionalidade ou melhoria para o sistema
title: "[FEATURE] "
labels: ["enhancement", "feature-request"]
assignees:
  - copilot
body:
  - type: markdown
    attributes:
      value: |
        ## Solicitar Nova Funcionalidade
        Use este formulário para propor novas funcionalidades ou melhorias significativas no sistema.

  - type: dropdown
    id: feature-area
    attributes:
      label: Área da Funcionalidade
      description: Qual parte do sistema esta funcionalidade afeta?
      options:
        - Gestão de Atividades
        - Inscrições de Estudantes
        - Autenticação e Permissões
        - Interface do Usuário
        - Filtros e Busca
        - Relatórios e Estatísticas
        - Notificações
        - API/Integrações
        - Outra
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Descrição da Funcionalidade
      description: Descreva detalhadamente a funcionalidade desejada
      placeholder: "Ex: Gostaria de poder exportar a lista de participantes de cada atividade em formato CSV para facilitar relatórios"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problema que Resolve
      description: Que problema ou necessidade esta funcionalidade atende?
      placeholder: "Ex: Atualmente é difícil gerar relatórios de participação para a administração da escola"
    validations:
      required: true

  - type: textarea
    id: current-workaround
    attributes:
      label: Como Você Faz Atualmente
      description: Como você resolve este problema hoje? Qual é o processo manual?
      placeholder: "Ex: Tenho que copiar manualmente cada email da interface e colar em uma planilha"
    validations:
      required: false

  - type: textarea
    id: proposed-solution
    attributes:
      label: Solução Proposta
      description: Como você imagina que esta funcionalidade funcionaria?
      placeholder: |
        Ex:
        1. Botão "Exportar" em cada atividade
        2. Ao clicar, gera arquivo CSV com nome, email, data de inscrição
        3. Download automático do arquivo
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Prioridade
      description: Qual a importância desta funcionalidade?
      options:
        - Alta - Necessidade urgente ou crítica
        - Média - Importante mas não urgente
        - Baixa - Seria bom ter mas não é essencial
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: Quem se Beneficiaria
      description: Quem utilizaria principalmente esta funcionalidade?
      options:
        - Professores
        - Administradores
        - Estudantes (indiretamente)
        - Todos
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Critérios de Aceitação
      description: Como saberemos que a funcionalidade está completa e funcionando?
      placeholder: |
        - [ ] Botão de exportar visível em cada atividade
        - [ ] Arquivo CSV gerado com campos corretos
        - [ ] Download funciona em todos navegadores principais
        - [ ] Dados exportados são precisos
      value: |
        - [ ]
        - [ ]
        - [ ]
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Exemplos ou Referências
      description: Conhece algum sistema similar que implementa isso? Tem screenshots ou mockups?
      placeholder: "Ex: O sistema X tem uma funcionalidade parecida que funciona assim..."
    validations:
      required: false

  - type: checkboxes
    id: breaking-changes
    attributes:
      label: Impacto
      description: Esta funcionalidade pode afetar funcionalidades existentes?
      options:
        - label: Pode afetar funcionalidades existentes
        - label: Requer mudanças no banco de dados
        - label: Requer mudanças na API
        - label: Requer mudanças na interface
        - label: Requer novas bibliotecas/dependências

  - type: textarea
    id: technical-notes
    attributes:
      label: Notas Técnicas (Opcional)
      description: Se você tem ideias sobre a implementação técnica, compartilhe aqui
      placeholder: |
        Ex:
        - Poderia usar biblioteca Apache Commons CSV
        - Adicionar endpoint GET /activities/{name}/export
        - Frontend faz chamada e dispara download
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        ### 📋 Critérios de Aceitação Padrão

        A funcionalidade será considerada completa quando:
        - ✅ Todos os critérios de aceitação específicos forem atendidos
        - ✅ A funcionalidade for testada manualmente e funcionar conforme esperado
        - ✅ Testes automatizados forem adicionados (unitários e/ou integração)
        - ✅ A documentação for atualizada (README, comentários no código)
        - ✅ O código seguir os padrões arquiteturais do projeto (Clean Architecture)
        - ✅ Os testes existentes continuarem passando
        - ✅ Não houver regressão em funcionalidades existentes

        ### 🔧 Informações Técnicas para o Agente Copilot

        **Princípios de Implementação:**
        - Seguir Clean Architecture: Domain → Application → Infrastructure → Presentation
        - Adicionar validações na camada de Domain quando aplicável
        - Criar casos de uso na camada Application para orquestrar lógica
        - Implementar endpoints REST na camada Presentation
        - Usar DTOs para comunicação externa

        **Estrutura de Implementação:**
        1. **Domain**: Adicionar entidades, value objects ou métodos de domínio necessários
        2. **Application**: Criar ou modificar casos de uso (UseCases) e DTOs
        3. **Infrastructure**: Adicionar configurações, migrations ou implementações de repositório
        4. **Presentation**: Criar/modificar controllers e mappers
        5. **Frontend**: Atualizar HTML/CSS/JS em `src/main/resources/static/`

        **Padrões de Código:**
        - Injeção de dependência via construtor
        - Validações auto-contidas em entities e value objects
        - Retorno de ResponseEntity<?> em controllers
        - Uso de Map.of("detail", message) para erros
        - Testes com JUnit 5 e Mockito

        **Checklist de Implementação:**
        - [ ] Camada Domain modificada/criada
        - [ ] Caso de uso implementado
        - [ ] Controller/endpoint criado
        - [ ] Frontend atualizado (se aplicável)
        - [ ] Testes unitários adicionados
        - [ ] Testes de integração adicionados (se aplicável)
        - [ ] Documentação atualizada
        - [ ] Migration criada (se mudanças no DB)
