blank_issues_enabled: false
contact_links:
  - name: Documentação do Sistema
    url: https://github.com/gucamara/java-copilot-code-agent/blob/main/docs/README.md
    about: Consulte a documentação completa do sistema para mais informações
